// Code generated by goctl. DO NOT EDIT.
// Source: account.proto

package server

import (
	"context"

	"go-zero-demo/cmd/account-rpc/internal/logic"
	"go-zero-demo/cmd/account-rpc/internal/svc"
	"go-zero-demo/cmd/account-rpc/pb"
)

type AccountRpcServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAccountRpcServiceServer
}

func NewAccountRpcServiceServer(svcCtx *svc.ServiceContext) *AccountRpcServiceServer {
	return &AccountRpcServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountRpcServiceServer) GenerateToken(ctx context.Context, in *pb.GenerateTokenReq) (*pb.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

func (s *AccountRpcServiceServer) ValidateToken(ctx context.Context, in *pb.TokenValidateReq) (*pb.TokenValidateResp, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}
