version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-latest
    ports:
      - "8888:8081" #访问主机端口8888,映射到容器端口8081,nginx在Docker内的端口为8081
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx

  account:
    image: account:1.0.0
    container_name: account-api
    ports:
      - "8002:8002"
    volumes:
      - ./account/etc/account-api.yaml:/usr/local/bin/account/etc/account-api.yaml
    networks:
      - default
      - external_network

  account-rpc:
    image: account-rpc:1.0.0
    container_name: account-rpc
    ports:
      - "8003:8003"
    volumes:
      - ./account-rpc/etc/account.yaml:/usr/local/bin/account-rpc/etc/account.yaml

  userinfo-api:
    image: userinfo-api:1.0.0
    container_name: userinfo-api
    ports:
      - "8006:8006"
    volumes:
      - ./userinfo-api/etc/userinfo-api.yaml:/usr/local/bin/userinfo-api/etc/userinfo-api.yaml

networks:
  external_network:
    external:
      name: chat-services_default
